"""S5 J21 - documents and chunks with pgvector
Revision ID: 0604f8766a70
Revises: c199d30fe196
Create Date: 2026-06-30 10:36:01.175672
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0604f8766a70'
down_revision: Union[str, None] = 'c199d30fe196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'page_count')
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###