"""s5 j40 add has_seen_welcome to users

Revision ID: 1a89bfa5cd01
Revises: ac8ec9ce91ff
Create Date: 2026-07-22 20:01:13.419183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a89bfa5cd01'
down_revision: Union[str, None] = 'ac8ec9ce91ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: drift pre-existant model/DB sur l'index vectoriel pgvector,
    # retire volontairement (sans lien avec ce changement, voir migrations
    # precedentes).
    op.add_column('users', sa.Column('has_seen_welcome', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_welcome')
    # ### end Alembic commands ###
