"""s5 j34: add corpus_id to conversations

Revision ID: 5537111fb7dc
Revises: 55dc638e085f
Create Date: 2026-07-15 18:53:04.143526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5537111fb7dc'
down_revision: Union[str, None] = '55dc638e085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('corpus_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_corpus_id'), 'conversations', ['corpus_id'], unique=False)
    op.create_foreign_key(
        'conversations_corpus_id_fkey',
        'conversations', 'corpora', ['corpus_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_corpus_id_fkey', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_corpus_id'), table_name='conversations')
    op.drop_column('conversations', 'corpus_id')
    # ### end Alembic commands ###
