"""s5 j41 add tokens cost and attachments to messages

Revision ID: 610dc04b7c0c
Revises: 1a89bfa5cd01
Create Date: 2026-07-23 19:20:56.062563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '610dc04b7c0c'
down_revision: Union[str, None] = '1a89bfa5cd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: drift pre-existant model/DB sur l'index vectoriel pgvector,
    # retire volontairement (sans lien avec ce changement).
    op.add_column('messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('cost_usd', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('model_used', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachments')
    op.drop_column('messages', 'model_used')
    op.drop_column('messages', 'cost_usd')
    op.drop_column('messages', 'total_tokens')
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    # ### end Alembic commands ###
