"""add personas tables and conversation persona_id

Revision ID: b3a5a383b9df
Revises: c91f39a0c428
Create Date: 2026-08-06 11:16:16.640830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a5a383b9df'
down_revision: Union[str, None] = 'c91f39a0c428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('personas_corpora',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('corpus_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('persona_id', 'corpus_id')
    )
    op.create_table('personas_documents',
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('persona_id', 'document_id')
    )
    op.add_column('conversations', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_persona_id'), 'conversations', ['persona_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_persona_id'), table_name='conversations')
    op.drop_column('conversations', 'persona_id')
    op.drop_table('personas_documents')
    op.drop_table('personas_corpora')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
