"""s5 j38: add pending column overrides to dataset

Revision ID: c8a38bd740dc
Revises: 09a9815b68ce
Create Date: 2026-07-21 11:32:40.190573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a38bd740dc'
down_revision: Union[str, None] = '09a9815b68ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('pending_column_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'pending_column_overrides')
    # ### end Alembic commands ###
