"""add include_attachments to conversation_shares

Revision ID: c91f39a0c428
Revises: fb2537909776
Create Date: 2026-08-05 13:45:12.045611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91f39a0c428'
down_revision: Union[str, None] = 'fb2537909776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_shares', sa.Column('include_attachments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_shares', 'include_attachments')
    # ### end Alembic commands ###
