"""s5 j32: add file_type to documents

Revision ID: e3551be3c5eb
Revises: f497afe85423
Create Date: 2026-07-15 13:22:51.024379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3551be3c5eb'
down_revision: Union[str, None] = 'f497afe85423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(length=10), server_default='pdf', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
