"""s5 j30: add feedback column to messages

Revision ID: f497afe85423
Revises: 85b0ff79d759
Create Date: 2026-07-15 01:49:35.413241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f497afe85423'
down_revision: Union[str, None] = '85b0ff79d759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback')
    # ### end Alembic commands ###
